language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-grover' ]; then cd .. && eval "mv $currentfolder generator-grover" && cd generator-grover; fi

